# Generated by Django 2.1.5 on 2019-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_cod',
            field=models.CharField(blank=True, choices=[('', '---'), ('701', 'Kho Bac Nha Nuoc'), ('201', '(VietinBank) - NH TMCP Cong Thuong'), ('202', '(BIDV) - NH TMCP Dau Tu va Phat trien Viet Nam'), ('203', '(VCB) - NH TMCP Ngoai Thuong'), ('204', '(AgriBank) - NH Nong Nghiep va PT Nong Thon'), ('207', '(VBSP) NH CHINH SACH XA HOI'), ('208', '(VDB) - NH Phat trien Viet Nam'), ('302', '(MSB) - NH TMCP Hang Hai Viet Nam'), ('630', 'First Commercial Bank CN TP HCM'), ('631', 'Ngan Hang Kookmin CN TP Ho Chi Minh'), ('632', 'Far East National Bank Hoi so Hoi so'), ('635', '(Maybank) - Malayan Banking Berhad'), ('636', 'Sumitomo Mitsui Bank'), ('638', '(BIDC) -NH DTPT Campuchia CN HA NOI'), ('639', 'Mizuho Bank TP HCM'), ('640', 'Hua Nan Commercial Bank TP HCM'), ('641', 'Industrial Bank of Korea(Cong nghiep HQ)TPHCM'), ('642', 'NH Taipei Fubon CN Ha Noi'), ('648', '(BIDC) - NH Dau Tu va Phat Trien Campuchia'), ('649', 'ICBC of China CN Ha Noi'), ('650', 'Ngan hang DBS Bank Ltd CN TPHCM'), ('651', 'NH TM Taipei Fubon CN TPHCM'), ('652', 'NH CONG NGHIEP HAN QUOC CN HA NOI'), ('653', 'Bank of Tokyo Mitsubishi UFJ Ltd CN Ha Noi'), ('654', '(CitiBank) - NH Citi Bank Viet Nam'), ('655', 'NH Taipei Fubon CN Binh Duong'), ('656', '(HANA) - Ng&acirc;n h&agrave;ng HANA CN TP.HCM'), ('657', 'NH BNP Paribas CN Ha Noi'), ('660', 'Ngan hang Busan - Chi nhanh TPHCM'), ('661', '(CIMB) - NH TNHH MTV CIMB VIET NAM'), ('662', 'NGAN HANG NONGHYUP - CN HA NOI'), ('663', 'NGAN HANG TNHH MTV WOORI VIET NAM'), ('901', '(Co-op Bank) - NH Hop Tac Xa Viet Nam'), ('101', 'NGAN HANG NHA NUOC'), ('600', 'THE SIAM COMMERCIAL BANK PUBLIC HCM'), ('658', 'NH TNHH E.SUN CN DONG NAI'), ('659', 'BANK OF INDIA CN TP HO CHI MINH'), ('303', '(STB) - NH TMCP Sai Gon Thuong Tin'), ('304', '(DONGABANK) - NH TMCP Dong A'), ('305', '(EIB) - NH TMCP Xuat Nhap Khau'), ('306', '(NamA) - NH TMCP Nam A'), ('307', '(ACB) - NH TMCP A Chau'), ('308', '(SaiGonBank)-NH TMCP Sai Gon Cong Thuong'), ('309', '(VP Bank) - NH TMCP Viet Nam Thinh Vuong'), ('310', '(Techcom Bank)-NH TMCP Ky Thuong VN'), ('311', '(MB) - NH TMCP Quan Doi'), ('313', '(NASB) - NH TMCP Bac A'), ('314', '(VIB) - NH TMCP Quoc Te'), ('317', '(SeABank) - NH TMCP Dong Nam A'), ('319', '(OceanBank) - NH TMCP Dai Duong'), ('320', '(GPB) - NH TMCP Dau Khi Toan Cau'), ('321', '(HD Bank) - NH TMCP PT Nha TpHCM'), ('323', '(ABB) - NH TMCP An Binh'), ('327', '(VCCB) - NH TMCP Ban Viet'), ('333', '(OCB) - NH TMCP Phuong Dong'), ('339', '(VNCB) - NH TMCP Xay Dung Viet Nam'), ('341', '(PGB) - NH TMCP Xang Dau Petrolimex'), ('348', '(SHB) - NH TMCP Sai Gon Ha Noi'), ('352', '(NCB) - NH TMCP Quoc Dan'), ('353', '(KienLong) - NH TMCP Kien Long'), ('355', '(VAB) - NH TMCP Viet A'), ('356', '(VietBank) - NH TMCP Viet Nam Thuong Tin'), ('357', '(LienVietPostBank) - NH TMCP Buu Dien Lien Viet'), ('358', '(TienPhongBank) - NH TMCP Tien Phong'), ('359', '(BVB) - NH TMCP Bao Viet'), ('360', '(PVcomBank) - NH TMCP Dai Chung Viet Nam'), ('401', 'Banknet Ha noi'), ('501', '(VID PB) - VID Public Bank'), ('502', '(IVB) - NH Indovina'), ('505', '(VRB) - NH Viet - Nga'), ('601', 'NH BPCEIOM CN TP HCM'), ('602', '(ANZ) - ANZ Viet Nam'), ('603', '(HLBVN) - NH Hong Leong Viet Nam'), ('604', 'Standard Chartered Viet Nam'), ('605', '(CitiBank) -CITI BANK Ha Noi'), ('606', 'NH The Shanghai Commercial Savings CN Dong Nai'), ('608', 'First Commercial Bank CN HA NOI'), ('609', 'MAY BANK Ha Noi'), ('611', 'China Construction Bank Corporation CN TP HCM'), ('612', 'BANGKOK BANK HCM'), ('613', 'Mizuho Bank'), ('614', 'BNP-PARIBAS HCM'), ('615', 'Bank of Communications CN TP HCM'), ('616', '(SHBVN) - NH TNHH MTV Shinhan VN'), ('617', '(HSBC) - NH TNHH mot thanh vien HSBC VN'), ('665', '(UOB) NH TNHH MTV United Overseas Bank VN'), ('619', '(DeutscheBank) - Deutsche Bank Viet Nam'), ('620', 'BANK OF CHINA HCM'), ('622', 'Tokyo - Mitsubishi UFJ'), ('623', 'Mega ICBC TP HCM'), ('625', 'Oversea - Chinese banking TP HCM'), ('626', 'KOREA EXCHANGE BANK Ha Noi'), ('627', 'JPMORGAN CHASE N.A TP HCM'), ('629', 'NH Thuong mai Chinatrust')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_facebook',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lazada_shop',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='online_sales_experience',
            field=models.CharField(blank=True, choices=[('', '---'), ('less_than_1', 'Dưới 1 năm'), ('1_to_3', '1-3 năm'), ('more_than_3', 'Trên 3 năm')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_facebook',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shopee_shop',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiki_shop',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---'), ('female', 'Nữ'), ('male', 'Nam')], max_length=32, null=True),
        ),
    ]
