# Generated by Django 2.1.5 on 2019-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190225_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='internal_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True, null=True, verbose_name='Interests'),
        ),
    ]
