# Generated by Django 2.1.7 on 2019-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190409_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_interaction_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
