# Generated by Django 2.1.7 on 2019-04-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_last_interaction_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_order_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
