# Generated by Django 2.1.7 on 2019-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190421_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='post_transaction_balance',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
