# Generated by Django 2.2 on 2019-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_communication_communicationresponse_communicationstatus_communicationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='failed',
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='one_signal_count',
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='remaining',
            field=models.IntegerField(default=-1, editable=False),
        ),
    ]
