# Generated by Django 2.2 on 2019-05-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190423_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationstatus',
            options={'verbose_name': 'Communication Status', 'verbose_name_plural': 'Communication Statuses'},
        ),
    ]
