# Generated by Django 2.2 on 2019-05-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190502_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationstatus',
            options={'verbose_name': 'Communication status', 'verbose_name_plural': 'Communication statuses'},
        ),
    ]
