# Generated by Django 2.2 on 2019-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190505_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, help_text='ID of referred object', max_length=128, null=True),
        ),
    ]
