# Generated by Django 2.2 on 2019-05-17 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0023_auto_20190509_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_update_referred_by', 'Can change referred_by'), ('can_update_cared_by', 'Can change cared_by'))},
        ),
        migrations.AddField(
            model_name='profile',
            name='cared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carers', to=settings.AUTH_USER_MODEL),
        ),
    ]
