# Generated by Django 2.2 on 2020-06-05 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_user_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', related_query_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
