# Generated by Django 2.1.5 on 2019-01-18 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paddington.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('customer_name', models.CharField(max_length=256)),
                ('customer_phone', models.CharField(max_length=256)),
                ('total_fee', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('night_fee', models.IntegerField(default=0)),
                ('stop_fee', models.IntegerField(default=0)),
                ('wait_fee', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_modified', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, paddington.models.SignalSaveMixin),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('start_point', models.CharField(max_length=1024)),
                ('end_point', models.TextField(max_length=1024)),
                ('stop_points', models.TextField(blank=True, null=True)),
                ('num_stop_points', models.IntegerField(default=0)),
                ('trip_distance', models.IntegerField()),
                ('trip_duration', models.IntegerField()),
                ('trip_type', models.IntegerField(default=0)),
                ('num_seats', models.IntegerField(default=4)),
                ('wait_time', models.IntegerField(default=0)),
                ('is_round_trip', models.BooleanField(default=False)),
                ('is_long_distance_trip', models.BooleanField(default=False)),
                ('return_trip_distance', models.IntegerField(default=0)),
                ('pickup_datetime', models.DateTimeField()),
                ('total_fee', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('night_fee', models.IntegerField(default=0)),
                ('stop_fee', models.IntegerField(default=0)),
                ('wait_fee', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, paddington.models.SignalSaveMixin),
        ),
        migrations.AddField(
            model_name='booking',
            name='quotation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='noibaiconnect.Quotation'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('created_by', 'quotation')},
        ),
    ]
