# Generated by Django 2.1.5 on 2019-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noibaiconnect', '0003_auto_20190128_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_id',
            field=models.CharField(editable=False, max_length=256, null=True, verbose_name='Supplier ref. no.'),
        ),
    ]
