# Generated by Django 2.1.5 on 2019-02-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noibaiconnect', '0004_auto_20190130_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã nhận'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy')], db_index=True, default='pending', editable=False, max_length=32)),
                ('driver_name', models.CharField(editable=False, max_length=256, null=True)),
                ('driver_number', models.CharField(editable=False, max_length=32, null=True)),
                ('plate', models.CharField(editable=False, max_length=32, null=True)),
                ('cancel_reason', models.TextField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Booking status',
                'verbose_name_plural': 'Booking status',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã nhận'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='pending', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='booking',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='noibaiconnect.Booking'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingstatus',
            unique_together={('booking', 'status')},
        ),
    ]
