# Generated by Django 2.1.5 on 2019-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noibaiconnect', '0005_auto_20190220_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
