# Generated by Django 2.2 on 2019-08-08 15:21

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('campaign_id', models.CharField(editable=False, max_length=32)),
                ('ip_address', models.CharField(editable=False, max_length=256)),
                ('success', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'unique_together': {('campaign_id', 'ip_address')},
            },
        ),
    ]
