# Generated by Django 2.2 on 2019-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipblock',
            old_name='success',
            new_name='is_on',
        ),
        migrations.AddField(
            model_name='ipblock',
            name='criterion_id',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
