# Generated by Django 2.1.5 on 2019-02-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20190227_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='VND')),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='merchandise.Product')),
            ],
            options={
                'verbose_name': 'Pricing policy',
                'verbose_name_plural': 'Pricing policies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'max_quantity')},
        ),
    ]
