# Generated by Django 2.1.5 on 2019-03-02 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paddington.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandise', '0003_auto_20190227_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(editable=False, max_length=256, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(help_text='Price client sent to us')),
                ('amount', models.PositiveIntegerField(editable=False)),
                ('price_by_system', models.PositiveIntegerField(editable=False, help_text='Price calculated by our backend', null=True)),
                ('amount_by_system', models.PositiveIntegerField(editable=False, help_text='Amount calculated by our backend', null=True)),
                ('deliver_to_me', models.BooleanField()),
                ('receiver_name', models.CharField(max_length=128)),
                ('receiver_phone', models.CharField(max_length=32)),
                ('receiver_address', models.TextField()),
                ('delivery_note', models.TextField(blank=True, null=True)),
                ('collect_on_behalf', models.BooleanField()),
                ('collection_money', models.PositiveIntegerField()),
                ('client_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_modified', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchandise.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, paddington.models.SignalSaveMixin),
        ),
    ]
