# Generated by Django 2.1.5 on 2019-03-09 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paddington.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandise', '0005_auto_20190306_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('status', models.CharField(choices=[('new', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('ready_to_ship', 'Sẵn sàng giao hàng'), ('dispatched', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('completed', 'Đã hoàn thành và thanh toán'), ('cancelled', 'Đã huỷ'), ('problem', 'Gặp vấn đề')], default='new', max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderstatus_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderstatus_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order status',
                'verbose_name_plural': 'Order statuses',
            },
            bases=(models.Model, paddington.models.SignalSaveMixin),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('ready_to_ship', 'Sẵn sàng giao hàng'), ('dispatched', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('completed', 'Đã hoàn thành và thanh toán'), ('cancelled', 'Đã huỷ'), ('problem', 'Gặp vấn đề')], db_index=True, default='new', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together={('order', 'status')},
        ),
    ]
