# Generated by Django 2.1.7 on 2019-03-16 10:23

from django.db import migrations, models
import django.db.models.deletion
import paddington.images


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_auto_20190309_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRendition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', models.ImageField(height_field='height', upload_to=paddington.images.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='merchandise.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='collect_on_behalf',
            field=models.BooleanField(verbose_name='Cash on delivery'),
        ),
        migrations.AlterUniqueTogether(
            name='imagerendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
    ]
