# Generated by Django 2.1.7 on 2019-03-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0009_auto_20190316_1807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together=set(),
        ),
    ]
