# Generated by Django 2.1.7 on 2019-03-20 13:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paddington.images
import paddington.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandise', '0010_auto_20190318_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrainingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('image', models.ImageField(upload_to='training_post/%Y%m%d/%H%M%S/')),
                ('title', models.CharField(max_length=512)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('published', models.BooleanField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainingpost_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainingpost_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, paddington.models.SignalSaveMixin),
        ),
        migrations.CreateModel(
            name='TrainingPostImageRendition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', models.ImageField(height_field='height', upload_to=paddington.images.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='merchandise.TrainingPost')),
            ],
        ),
        migrations.AddField(
            model_name='producttrainingpost',
            name='training_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.TrainingPost'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingpostimagerendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
        migrations.AlterUniqueTogether(
            name='producttrainingpost',
            unique_together={('product', 'training_post')},
        ),
    ]
