# Generated by Django 2.1.7 on 2019-04-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0015_auto_20190402_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
