# Generated by Django 2.1.7 on 2019-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0017_auto_20190404_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
