# Generated by Django 2.1.7 on 2019-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0018_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories_vn',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_vn',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.TextField(editable=False, null=True),
        ),
    ]
