# Generated by Django 2.1.7 on 2019-04-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0019_auto_20190404_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['created_at'], 'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
    ]
