# Generated by Django 2.2 on 2019-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0027_auto_20190502_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_specification',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
