# Generated by Django 2.2 on 2019-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0031_auto_20190505_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-ordering_score'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering_score',
            field=models.FloatField(default=0),
        ),
    ]
